name: rlf
version: 0.0.1
author: Jim Simon <jim.j.simon@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  recase: "^1.0.0+1"
  shelf_route: "^0.14.3"

dev_dependencies:
  test: ^0.12.0
