name: rlf
version: 0.0.1
author: Jim Simon <jim.j.simon@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  path: "^1.5.1"
  recase: "^1.0.0+1"
  shelf_route: "^0.14.3"
  vm_service_lib: "^0.3.5+2"
#  vm_service_client:
#    git:
#      url: git@github.com:BlackHC/vm_service_client.git
#      ref: reload_sources

dev_dependencies:
  test: ^0.12.0
